config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  resources :lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks, dependent: :destroy
    validates :name, presence: true,
                    length: { minimum: 5 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :name, presence: true,
                    length: { minimum: 5 }
  validates :description, presence: true,
                    length: { maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
        @lists = List.all
    end
    
    def show
        @list = List.find(params[:id])
    end
    
    def new
        @list = List.new
    end
    
    def edit
        @list = List.find(params[:id])
    end

    def create
        
        @list = List.new(list_params)

        if @list.save
            redirect_to @list
        else
            render 'new'
        end

    end

    def update
        @list = List.find(params[:id])
       
        if @list.update(list_params)
          redirect_to @list
        else
          render 'edit'
        end
    end
    def destroy
        @list = List.find(params[:id])
        @list.destroy
       
        redirect_to lists_path
    end
   

    private
    def list_params
        params.require(:list).permit(:name, :description, :completed)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def show
      @list = List.find(params[:id])
    end
  


    def create
        @list = List.find(params[:list_id])
        @task = @list.tasks.create(task_params)

    end

     
    def destroy
      @list = List.find(params[:list_id])
      @task = @list.tasks.find(params[:id])
      @task.destroy
      redirect_to list_path(@list)
    end

    private
        def task_params
          params.require(:task).permit(:name, :description, :priority, :status, :due, :completed)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def yesno(x)
        x ? "Yes" : "No"
    end


end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: @list, local: true) do |form| %>
 
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
  </p>
    
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
    
  <p>
    <%= form.label :completed %><br>
    <%= form.check_box :completed, {}, "true", "false" %> <br />
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/lists/edit.html.erb
<h1>Edit Todo List</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing Todo Lists</h1>
<%= link_to 'New list', new_list_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Completed</th>
    
    <th></th>
  </tr>
 
  <% @lists.each do |list| %>
    <tr>
      <td><%= list.name %></td>
      <td><%= list.description %></td>
      <td><%= yesno(list.completed) %></td>
      
      <td><%= link_to 'Show', list_path(list) %></td>
      <td><%= link_to 'Edit', edit_list_path(list) %></td>
      <td><%= button_to 'Delete', list_path(list),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>
 
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= yesno(@list.completed) %>
</p>

<h2>Tasks</h2>
<table border=1>
  <tr>
    <th width=100>Name</th>
    <th width=300>Description</th>
    <th width=100>Priority</th>
    <th width=100>Status</th>
    <th width=100>Due</th>
    <th width=100>Completed</th>
    
    
  </tr>
  </table>
<%= render @list.tasks %>

<h2>Add a task:</h2>
<%= render 'tasks/form' %>

<%= link_to 'Edit', edit_list_path(@list) %> 
<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_with(model: [ @list, @list.tasks.build ], local: true) do |form| %>
    
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.label :priority %><br>
      <%= form.select :priority, ["Critical","High","Medium","Low"]%>
    </p>
    <p>
      <%= form.label :status %><br>
      <%= form.select :status, ["New","In Progress","Requires Moderation","Finished"]%>
    </p>
    <p>
      <%= form.label :due %><br>
      <%= form.date_field :due %>
    </p>
    <p>
      <%= form.label :completed %><br>
      <%= form.check_box :completed, {}, "true", "false" %> 
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/tasks/_task.html.erb
<table border=1>
    <tr>
      <td width=100><%= task.name %></td>
      <td width=300><%= task.description %></td>
      <td width=100><%= task.priority %></td>
      <td width=100><%= task.status %></td>
      <td width=100><%= task.due %></td>
      <td width=100><%= yesno(task.completed) %></td>
      
      <td><%= button_to 'Delete Task', [task.list, task],
               method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
    </tr>

</table>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
<strong>Name:</strong>
<%= @list.name %>
</p>

<p>
<strong>Description:</strong>
<%= @list.description %>
</p>

<p>
<strong>Completed:</strong>
<%= yesno(@list.completed) %>
</p>

<h2>Tasks</h2>
<table border=1>
<tr>
  <th width=100>Name</th>
  <th width=300>Description</th>
  <th width=100>Priority</th>
  <th width=100>Status</th>
  <th width=100>Due</th>
  <th width=100>Completed</th>
  
  
</tr>
</table>
<%= render @list.tasks %>

<h2>Add a task:</h2>
<%= render 'tasks/form' %>

<%= link_to 'Edit', edit_list_path(@list) %> 
<%= link_to 'Back', lists_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<%= link_to 'My Todo List', controller: 'lists' %>
<p>Find me in app/views/welcome/index.html.erb</p>